version: '3.3'

services:
    event_store:
        container_name: eventstore
        image: eventstore/eventstore:release-5.0.8
        restart: unless-stopped
        ports:
          - 1113:1113
          - 2113:2113
    redis:
        container_name: redis
        image: redis:4
        ports:
          - 6379:6379
    seb_command:
        container_name: seb-command
        image: culaja/scalableeventbus:1.0
        restart: unless-stopped
        command: ["dotnet", "ScalableEventBus.dll"]
        environment:
          - 'Application__EventStoreConnectionString=tcp://admin:changeit@eventstore:1113'
          - 'Application__StreamPrefix=Domain'
          - 'Application__DestinationServiceUri=http://host.docker.internal:5000/DomainEvent/Apply'
    seb_query:
        container_name: seb-query
        image: culaja/scalableeventbus:1.0
        restart: unless-stopped
        command: ["dotnet", "ScalableEventBus.dll"]
        environment:
          - 'Application__EventStoreConnectionString=tcp://admin:changeit@eventstore:1113'
          - 'Application__StreamPrefix=Domain'
          - 'Application__DestinationServiceUri=http://host.docker.internal:10000/DomainEvent/Apply'